AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An Amazon SNS trigger that sends CloudWatch alarm notifications to Slack.
Resources:
  CWtoSlackEvents:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: .
      Description: >-
        An Amazon SNS trigger that sends CloudWatch alarm notifications to
        Slack.
      MemorySize: 128
      Timeout: 7
      Role: 'arn:aws:iam::408560555724:role/lambda_basic_instance'
      Events:
        SNS1:
          Type: SNS
          Properties:
            Topic:
              Ref: SNSTopic1
      Environment:
        Variables:
          kmsEncryptedHookUrl: >-
            AQICAHg8R4wL5j4PkWoFvqHRYRcQFlmXkFXzUUEJSF+EkhJPsAHt33597MYOoY0snytB9m/UAAAApzCBpAYJKoZIhvcNAQcGoIGWMIGTAgEAMIGNBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDBxSQv4vymhdYemSdgIBEIBgp1JALI0YXbA6oon+K/QOW48oewll68yXy5ZWv/4ZmoJmJGm4YmLBKf0KFK7C6HZytDKhfvefc9vG5oxe+rllnOmDTE3PAkUe7USCv1eXQd0Js6VEcQmrSNm91HpwpBR1
          slackChannel: aws-test
      Tags:
        'lambda-console:blueprint': cloudwatch-alarm-to-slack-python3
  SNSTopic1:
    Type: 'AWS::SNS::Topic'
